config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # root 'questions#index'
  resources :results

  resources :grills

  resources :questions

resources :questions do
  resources :grills do
    resources :results
  end
end

end

app/models/grill.rb
class Grill < ActiveRecord::Base
  belongs_to :question, inverse_of: :grills
  validates :question,
           presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base

has_many :grills, dependent: :destroy, inverse_of: :question

accepts_nested_attributes_for :grills
#add to tutorial
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :grill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grills_controller.rb
class GrillsController < ApplicationController
  before_action :set_grill, only: [:show, :edit, :update, :destroy]
  # GET /grills
  # GET /grills.json
  def index
    @grills = Grill.all
  end

  # GET /grills/1
  # GET /grills/1.json
  def show
    @grill = Grill.find(params[:id])
    @question = Grill.find(params[:id])
    @score = 0
    
    if :q1correct == :ans1
      @score += 1
    else
      @wrongone = "Wrong"
    end
  end

  # GET /grills/new
  def new
  #PUT IT IN ORDER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  #MAKE SURE YOU CALL THE QUESTION FIND FIRST OR YOU WILL GET A NILL ERROR
   @question = Question.find(params[:question_id]) #ADD TO TUTORIAL
    @grill = @question.grills.create #ADD TO TUTORIAL
  end

  # GET /grills/1/edit
  def edit
  end

  # POST /grills
  # POST /grills.json
  def create
    @grill = Grill.new(grill_params)

    respond_to do |format|
      if @grill.save
        format.html { redirect_to @grill, notice: 'Grill was successfully created.' }
        format.json { render :show, status: :created, location: @grill }
      else
        format.html { render :new }
        format.json { render json: @grill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grills/1
  # PATCH/PUT /grills/1.json
  def update
    respond_to do |format|
      if @grill.update(grill_params)
        format.html { redirect_to @grill, notice: 'Grill was successfully updated.' }
        format.json { render :show, status: :ok, location: @grill }
      else
        format.html { render :edit }
        format.json { render json: @grill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grills/1
  # DELETE /grills/1.json
  def destroy
    @grill.destroy
    respond_to do |format|
      format.html { redirect_to grills_url, notice: 'Grill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grill
      @grill = Grill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grill_params
      params.require(:grill).permit(:ans1, :ans2, :ans3, :question_id, :grill_id)
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    @home_page = "true"
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:q1, :q1a, :q1b, :q1c, :q1d, :q1correct, 
      :q2, :q2a, :q2b, :q2c, :q2d, :q2correct, 
      :q3, :q3a, :q3b, :q3c, :q3d, :q3correct, 
      :grill_attributes => [ :id, :ans1, :ans2, :ans3, :ans4, :ans5, :ans6, :ans7, :ans8, :ans9, :ans10 ])
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
    @question = Question.find(params[:question_id])
    @grill = Grill.find(params[:grill_id])
    @score = 0
    @q1 = @question.q1correct
    @a1 = @grill.ans1
    @q2 = @question.q2correct
    @a2 = @grill.ans2    
    @q3 = @question.q3correct
    @a3 = @grill.ans3
    if @a1 == @q1
      @score += 1
    end
    if @a2 == @q2
      @score += 1
    end
    if @a3 == @q3
      @score += 1
    end
    if @score == 3
      @message = "Awesome! 3/3"
    end
    if @score == 2
      @message = "Not bad 2/3"
    end
    if @score == 1
      @message = "Try harder 1/3"
    end
    if @score == 0
      @message = "No correct answers 0/3"
    end
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:score, :grill_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grills_helper.rb
module GrillsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/grills/_form.html.erb
<%= form_for(@grill) do |f| %>
  <% if @grill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grill.errors.count, "error") %> prohibited this grill from being saved:</h2>

      <ul>
      <% @grill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
<%= @question.q1 %><br>
<%= f.label :ans1 %><br>
<%= f.radio_button :ans1, "a" %><%= @question.q1a %><br>
<%= f.radio_button :ans1, "b" %><%= @question.q1b %><br>
<%= f.radio_button :ans1, "c" %><%= @question.q1c %><br>
<%= f.radio_button :ans1, "d" %><%= @question.q1d %><br>
  </div>
  <div class="field">
<%= @question.q2 %><br>
<%= f.label :ans2 %><br>
<%= f.radio_button :ans2, "a" %><%= @question.q2a %><br>
<%= f.radio_button :ans2, "b" %><%= @question.q2b %><br>
<%= f.radio_button :ans2, "c" %><%= @question.q2c %><br>
<%= f.radio_button :ans2, "d" %><%= @question.q2d %><br>
  </div>
  <div class="field">
<%= @question.q3 %><br>
    <%= f.label :ans3 %><br>
<%= f.radio_button :ans3, "a" %><%= @question.q3a %><br>
<%= f.radio_button :ans3, "b" %><%= @question.q3b %><br>
<%= f.radio_button :ans3, "c" %><%= @question.q3c %><br>
<%= f.radio_button :ans3, "d" %><%= @question.q3d %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grills/edit.html.erb
<h1>Editing Grill</h1>

<%= render 'form' %>

<%= link_to 'Show', @grill %> |
<%= link_to 'Back', grills_path %>

app/views/grills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grills</h1>

<table>
  <thead>
    <tr>
      <th>Ans1</th>
      <th>Ans2</th>
      <th>Ans3</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grills.each do |grill| %>
      <tr>
        <td><%= grill.ans1 %></td>
        <td><%= grill.ans2 %></td>
        <td><%= grill.ans3 %></td>
        <td><%= grill.question %></td>
        <td><%= link_to 'Show', grill %></td>
        <td><%= link_to 'Edit', edit_grill_path(grill) %></td>
        <td><%= link_to 'Destroy', grill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grill', new_grill_path %>

app/views/grills/new.html.erb
<h1>New Grill</h1>

<%= render 'form' %>

<%= link_to 'Back', grills_path %>

app/views/grills/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="resultssuccess">I DID IT!!!</h1>
<%= link_to "See Results", new_question_grill_result_path(@question.question_id, @grill), class: "btn btn-default btn-lg" %></br></br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Q3app</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '753338594761413',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

</head>
<body style="<%= if @home_page == 'true'; 'background-color: orange' else 'background-color: pink' end%>">
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Question 1" %><br>
    <%= f.text_field :q1 %><br>
<%= f.radio_button :q1correct, "a" %><%= f.label "A. " %><%= f.text_field :q1a %><br>
<%= f.radio_button :q1correct, "b" %><%= f.label "B. " %><%= f.text_field :q1b %><br>
<%= f.radio_button :q1correct, "c" %><%= f.label "C. " %><%= f.text_field :q1c %><br>
<%= f.radio_button :q1correct, "d" %><%= f.label "D. " %><%= f.text_field :q1d %><br>
  </div>

  <div class="field">
    <%= f.label "Question 2" %><br>
    <%= f.text_field :q2 %><br>
<%= f.radio_button :q2correct, "a" %><%= f.label "A. " %><%= f.text_field :q2a %><br>
<%= f.radio_button :q2correct, "b" %><%= f.label "B. " %><%= f.text_field :q2b %><br>
<%= f.radio_button :q2correct, "c" %><%= f.label "C. " %><%= f.text_field :q2c %><br>
<%= f.radio_button :q2correct, "d" %><%= f.label "D. " %><%= f.text_field :q2d %><br>
  </div>

  <div class="field">
    <%= f.label "Question 3" %><br>
    <%= f.text_field :q3 %><br>
<%= f.radio_button :q3correct, "a" %><%= f.label "A. " %><%= f.text_field :q3a %><br>
<%= f.radio_button :q3correct, "b" %><%= f.label "B. " %><%= f.text_field :q3b %><br>
<%= f.radio_button :q3correct, "c" %><%= f.label "C. " %><%= f.text_field :q3c %><br>
<%= f.radio_button :q3correct, "d" %><%= f.label "D. " %><%= f.text_field :q3d %><br>
  </div>

  
  <div class="actions">
    <%= f.submit "CREATE NEW QUIZ" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Q1</th>
      <th>Q1a</th>
      <th>Q1b</th>
      <th>Q1c</th>
      <th>Q1d</th>
      <th>Q1correct</th>
      <th>Q2</th>
      <th>Q2a</th>
      <th>Q2b</th>
      <th>Q2c</th>
      <th>Q2d</th>
      <th>Q2correct</th>
      <th>Q3</th>
      <th>Q3a</th>
      <th>Q3b</th>
      <th>Q3c</th>
      <th>Q3d</th>
      <th>Q3correct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.q1 %></td>
        <td><%= question.q1a %></td>
        <td><%= question.q1b %></td>
        <td><%= question.q1c %></td>
        <td><%= question.q1d %></td>
        <td><%= question.q1correct %></td>
        <td><%= question.q2 %></td>
        <td><%= question.q2a %></td>
        <td><%= question.q2b %></td>
        <td><%= question.q2c %></td>
        <td><%= question.q2d %></td>
        <td><%= question.q2correct %></td>
        <td><%= question.q3 %></td>
        <td><%= question.q3a %></td>
        <td><%= question.q3b %></td>
        <td><%= question.q3c %></td>
        <td><%= question.q3d %></td>
        <td><%= question.q3correct %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<div class="outer">
<div class="middle">
<div class="inner-new-quiz center">
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

</div>
</div>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1:</strong>
  <%= @question.q1 %>
</p>

<p>
  <strong>Q1a:</strong>
  <%= @question.q1a %>
</p>

<p>
  <strong>Q1b:</strong>
  <%= @question.q1b %>
</p>

<p>
  <strong>Q1c:</strong>
  <%= @question.q1c %>
</p>

<p>
  <strong>Q1d:</strong>
  <%= @question.q1d %>
</p>

<p>
  <strong>Q1correct:</strong>
  <%= @question.q1correct %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @question.q2 %>
</p>

<p>
  <strong>Q2a:</strong>
  <%= @question.q2a %>
</p>

<p>
  <strong>Q2b:</strong>
  <%= @question.q2b %>
</p>

<p>
  <strong>Q2c:</strong>
  <%= @question.q2c %>
</p>

<p>
  <strong>Q2d:</strong>
  <%= @question.q2d %>
</p>

<p>
  <strong>Q2correct:</strong>
  <%= @question.q2correct %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @question.q3 %>
</p>

<p>
  <strong>Q3a:</strong>
  <%= @question.q3a %>
</p>

<p>
  <strong>Q3b:</strong>
  <%= @question.q3b %>
</p>

<p>
  <strong>Q3c:</strong>
  <%= @question.q3c %>
</p>

<p>
  <strong>Q3d:</strong>
  <%= @question.q3d %>
</p>

<p>
  <strong>Q3correct:</strong>
  <%= @question.q3correct %>
</p>
<br>
<%= link_to "Try it out", new_question_grill_path(@question), class: "btn btn-default btn-lg" %></br></br>
<br>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :grill_id %><br>
    <%= f.text_field :grill_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Grill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.score %></td>
        <td><%= result.grill %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>Results Page</h1>
<a href="https://twitter.com/share" class="twitter-share-button" data-text="I got grilled, yo!" data-via="grillten" data-size="large" data-hashtags="grill10">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<h3 class="score">
  Score: <%= @score %>
  Message: <%= @message %>
  Q 1: <%= @q1 %>
  Answer 1: <%= @a1 %>


</h3>

<h2 class="answersentered">
  Answers Entered
</h2>
<%= @grill.ans1 %><br>
<%= @grill.ans2 %><br>
<%= @grill.ans3 %><br>



<%= render 'form' %>

<%= link_to 'Back', results_path %>

<%= @question.q1 %>

<%= @grill.ans1 %>

<h1 class="questions">Question List</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1:</strong>
  <%= @question.q1 %>
</p>

<p>
  <strong>Q1a:</strong>
  <%= @question.q1a %>
</p>

<p>
  <strong>Q1b:</strong>
  <%= @question.q1b %>
</p>

<p>
  <strong>Q1c:</strong>
  <%= @question.q1c %>
</p>

<p>
  <strong>Q1d:</strong>
  <%= @question.q1d %>
</p>

<p>
  <strong>Q1correct:</strong>
  <%= @question.q1correct %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @question.q2 %>
</p>

<p>
  <strong>Q2a:</strong>
  <%= @question.q2a %>
</p>

<p>
  <strong>Q2b:</strong>
  <%= @question.q2b %>
</p>

<p>
  <strong>Q2c:</strong>
  <%= @question.q2c %>
</p>

<p>
  <strong>Q2d:</strong>
  <%= @question.q2d %>
</p>

<p>
  <strong>Q2correct:</strong>
  <%= @question.q2correct %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @question.q3 %>
</p>

<p>
  <strong>Q3a:</strong>
  <%= @question.q3a %>
</p>

<p>
  <strong>Q3b:</strong>
  <%= @question.q3b %>
</p>

<p>
  <strong>Q3c:</strong>
  <%= @question.q3c %>
</p>

<p>
  <strong>Q3d:</strong>
  <%= @question.q3d %>
</p>

<p>
  <strong>Q3correct:</strong>
  <%= @question.q3correct %>
</p>
<br>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @result.score %>
</p>

<p>
  <strong>Grill:</strong>
  <%= @result.grill %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>

app/views/welcome/index.html.erb
<div class="button-position">
<%= button_to 'CREATE A QUIZ', new_question_path, :class => "create-button", :method => "get" %>
</div>
<div class="outer">
<div class="middle">
<div class="inner-welcome">

<div class="main-welcome">
<h1>Welcome to Q3 Quiz</h1>
<p>A simple quiz web app</p>
</div>

</div>
</div>
</div>